config/routes.rb
Rails.application.routes.draw do
  resources :libraries, only: [:show, :new, :create, :index]
  resources :users, only: [:index, :new, :create, :update]
  resources :categories, only: [:index]
  resources :mechanics, only: [:index]
  resource :sessions, only: [:new, :create, :destroy]
  resource :profile, except: [:new, :create], controller: "users"

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  get '/games/:id', to: 'games#show'

  root to: 'users#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :games_categories
  has_many :games, through: :games_categories

  validates :bgg_id, uniqueness: true, presence: true
  validates :name, presence: true
end

app/models/favoritelibrary.rb
class Favoritelibrary < ActiveRecord::Base
  belongs_to :user
  belongs_to :library
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :games_categories
  has_many :categories, through: :games_categories

  has_many :games_mechanics
  has_many :mechanics, through: :games_mechanics

  has_many :games_libraries
  has_many :libraries, through: :games_libraries

  validates :bgg_id, uniqueness: true, presence: true
  validates :name, presence: true
end

app/models/games_category.rb
class GamesCategory < ActiveRecord::Base
  belongs_to :game
  belongs_to :category

  validates :game_id, presence: true
  validates :category_id, presence: true
end

app/models/games_library.rb
class GamesLibrary < ActiveRecord::Base
  belongs_to :game
  belongs_to :library

  validates :game_id, presence: true
  validates :library_id, presence: true
end

app/models/games_mechanic.rb
class GamesMechanic < ActiveRecord::Base
  belongs_to :game
  belongs_to :mechanic

  validates :game_id, presence: true
  validates :mechanic_id, presence: true
end

app/models/library.rb
class Library < ActiveRecord::Base
  has_many :games_libraries
  has_many :games, through: :games_libraries

  has_many :users

  has_many :favusers, class: "Favoritelibrary"
  has_many :favoriteusers, through: :favusers

  validates :bgg_username, presence: true
end

app/models/mechanic.rb
class Mechanic < ActiveRecord::Base
  has_many :games_mechanics
  has_many :games, through: :games_mechanics

  validates :bgg_id, uniqueness: true, presence: true
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  belongs_to :library

  has_many :favlibraries, class_name: "Favoritelibrary"
  has_many :favoritelibraries, through: :favlibraries

  validates :auth0_id, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  # before_action :authenticate

  def authenticate
    authenticate_token || render_unauthorized
  end

  def authenticate_token
    authenticate_or_request_with_http_token do |token, options|
      @user = User.find_by(auth_token: token)
    end
  end

  def render_unauthorized
    self.headers['WWW-Authenticate'] = 'Token realm="Application"'
    render json: 'Bad credentials', status: 401
  end

end

app/controllers/categories_controller.rb
class CategoriesController < SecuredController
  def index
    all_categories = Category.all
    render json: all_categories.to_json
  end
end

app/controllers/games_controller.rb
class GamesController < SecuredController
  skip_before_action :authenticate
  def show
    game = Game.find(params[:id])

    render json: game.to_json
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < SecuredController
  def index
    all_libraries = Library.all
    render json: all_libraries.to_json
  end

  def show
    all_games = Library.find_by(bgg_username: params[:id]).games.includes(:categories,:mechanics)

    json_games = all_games.map do |game|
      JSON::parse(game.to_json).merge({
        "mechanics"=> game.mechanics.map(&:name),
        "categories"=> game.categories.map(&:name),
      })
    end

    render json: json_games.to_json
  end

  def create
    user = User.find_by(auth0_id: params['token'])
    bgg_user = params['bgg_username']
    response = BggApi.new.collection({ username: bgg_user })
    if response.keys[0] != "error"
      library = Library.find_or_create_by(bgg_username: bgg_user)
      UsersFetcher.perform_async(bgg_user)
      user.library_id = library.id
      user.save
      message = 1
    else
      message = 0
    end
    render json: message.to_json
  end
end

app/controllers/mechanics_controller.rb
class MechanicsController < SecuredController
  def index
    all_mechanics = Mechanic.all
    render json: all_mechanics.to_json
  end
end

app/controllers/secured_controller.rb
class SecuredController < ApplicationController
  before_action :validate_token

  class InvalidTokenError < StandardError; end

  private

  def validate_token
    begin
      authorization = request.headers['Authorization']
      raise InvalidTokenError if authorization.nil?

      token = request.headers['Authorization'].split(' ').last
      decoded_token = JWT.decode(token,
        JWT.base64url_decode(Rails.application.secrets.auth0_client_secret))

      raise InvalidTokenError if Rails.application.secrets.auth0_client_id != decoded_token[0]["aud"]

      @user = decoded_token

      auth0_id = ClaimsPrincipal.Current.FindFirst("user_id").Value

      if User.find_by(auth0_id: auth0_id) == nil
        name = ClaimsPrincipal.Current.FindFirst("name").Value
        email = ClaimsPrincipal.Current.FindFirst("email").Value
        User.create(auth0_id: auth0_id, name: name, email: email)
      end

    rescue JWT::DecodeError, InvalidTokenError
      render :json => { :error => "Unauthorized: Invalid token." }, status: :unauthorized
    end
  end

end

app/controllers/users_controller.rb
class UsersController < SecuredController
  skip_before_action :authenticate, only: [:index, :new, :create]

  def index
    users = User.all
    render json: users, status: 200
  end

  def new
    @user = User.new
  end

  def create
    user = User.find_or_initialize_by(auth0_id: params["token"])
    user.name = params["name"] if params["name"]
    user.save
    render json: user.to_json
  end

  def show
    user = User.find(auth0_id: params[:auth0_id])
    render json: user.to_json
  end

  def update
    user = User.find_by(auth0_id: params[:auth0_id])
    user.update(params)
    render json: user.to_json
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameFinder</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <% if session[:user_id] %>
      <%= link_to "My Account", profile_path, class: "button" %>
      <%= link_to "Log Out", logout_path, class: "button" %>
    <% else %>
      <%= link_to "Log In", login_path, class: "button" %>
      <%= link_to "Sign Up", signup_path, class: "button" %>
    <% end %>
  </nav>
<%= yield %>
</body>
</html>

app/views/users/edit.html.erb
<h2>Update Information</h2>

<%= form_for @user, url: profile_path, method: :put  do |f| %>
  <% if @user.errors.any? %>
    <%= render 'error' %>
  <% end %>

  <%= f.label :name, "Name" %>
  <%= f.text_field :name, placeholder: "Name", autofocus: true, value: @user.name %> <br>
  <%= f.label :password, "Password" %>
  <%= f.password_field :password, placeholder: "Password", value: @user.password %> <br>
  <%= f.label :email, "Email" %>
  <%= f.text_field :email, placeholder: "Email", value: @user.email  %> <br>
  <%= f.label :phone, "Phone" %>
  <%= f.text_field :phone, placeholder: "Phone", value: @user.phone %> <br>
  <%= f.label :handle, "GameFinder Handle" %>
  <%= f.text_field :handle, placeholder: "GameFinder Handle", value: @user.handle %> <br>

  <%= f.submit "Submit Changes", :disable_with => 'Submiting...' %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <header>
    <h1><span>GameFinder</span></h1>
  </header>
  <p>
    Welcome to the GameFinder Portal!
  </p>
  <p>
    If you would like to search for a game, you can do so through the mobile app.
  </p>
  <p>
    To download the APK, please click <a href="#">here</a>.
  </p>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <%= render 'error' %>
  <% end %>

  <%= f.label :name, "Name" %>
  <%= f.text_field :name, placeholder: "Name" %> <br>
  <%= f.label :email, "Email" %>
  <%= f.text_field :email, autofocus: true, placeholder: "Email" %> <br>
  <%= f.label :password, "Password" %>
  <%= f.password_field :password, placeholder: "Password" %> <br>
  <%= f.label :password_confirmation, "Confirm Password" %>
   <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %> <br>

  <%= f.submit "Sign Up", :disable_with => 'Submiting...' %>
<% end %>

app/views/users/show.html.erb
<p class="success" id="notice"><%= notice %></p>
<h2>Account Information</h2>
<hr>
<table>
  <tr>
    <td>Name</td>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <td>Email</td>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <td>Phone</td>
    <td><%= @user.phone %></td>
  </tr>
  <tr>
    <td>BGG Handle</td>
    <td><%= @user.bgg_username %></td>
  </tr>
  <tr>
    <td>GameFinder Handle</td>
    <td><%= @user.handle %></td>
  </tr>
</table>

<%= link_to "Edit Account Information", edit_profile_path, class: "button" %>

<%= link_to "Delete Account", profile_path, method: :delete, class: "button",data: {confirm: "Are you sure?"} %>